name = "digeclip"
compatibility_date = "2023-12-01"

[build]
command = "npm install && NODE_OPTIONS='--max-old-space-size=4096' npm run build:cf"
cwd = "."
watch_dir = "src"
output_dir = "out"
node_compat = true

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
NODE_ENV = "production"
NEXT_PUBLIC_IS_CLOUDFLARE_PAGES = "true"

[site]
bucket = "out"
pages_build_output_dir = "out"

[env.production]
vars = { NODE_ENV = "production", NEXT_PUBLIC_IS_CLOUDFLARE_PAGES = "true" }

[env.preview]
vars = { NODE_ENV = "development", NEXT_PUBLIC_IS_CLOUDFLARE_PAGES = "true" }