name: Lint & Format

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, development]

# 権限設定
permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    steps:
      - uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'digeclip/package-lock.json'

      - name: 依存関係のインストール
        working-directory: digeclip
        run: npm ci

      - name: ESLintの実行
        working-directory: digeclip
        run: npm run lint

      - name: Prettierの実行
        working-directory: digeclip
        run: npm run format -- --check

      - name: 型チェックの実行
        working-directory: digeclip
        run: npm run type-check