name: Supabase デプロイ

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'digeclip/seeds/**'
      - '.github/workflows/supabase-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-supabase:
    name: Supabase スキーマデプロイ
    runs-on: ubuntu-latest
    timeout-minutes: 15  # ジョブの最大実行時間を設定

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: PostgreSQLクライアントのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Supabase CLIをインストール
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 環境変数の設定と適用
        run: |
          # プロジェクト構造の確認
          echo "プロジェクト構造を確認しています..."
          ls -la
          echo "digeclipディレクトリの内容:"
          ls -la digeclip/
          echo "seedsディレクトリの内容:"
          ls -la digeclip/seeds/

          # 環境変数を設定
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            # 開発環境の設定
            SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL_DEV }}"
            SUPABASE_KEY="${{ secrets.DEV_SUPABASE_SERVICE_ROLE_KEY }}"
            SUPABASE_PROJECT_ID=$(echo $SUPABASE_URL | sed 's|https://||' | sed 's|.supabase.co||')
            echo "環境: 開発環境 (シードデータ適用あり)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase プロジェクトID: $SUPABASE_PROJECT_ID"

            # スキーマを適用
            echo "開発環境のスキーマを適用しています..."
            export SUPABASE_ACCESS_TOKEN="${{ secrets.SUPABASE_ACCESS_TOKEN }}"
            export PGPASSWORD="${{ secrets.DEV_DB_PASSWORD }}"

            # CLIの接続テスト
            echo "Supabase CLI 接続テスト中..."
            supabase projects list --debug > cli_test.log 2>&1

            if [ $? -ne 0 ]; then
              echo "Supabase CLI接続テストに失敗しました。詳細:"
              cat cli_test.log | grep -v "password\|token\|secret\|key"
              exit 1
            else
              echo "Supabase CLI接続テスト成功"
            fi

            # スキーマファイルの確認
            if [ -f "digeclip/seeds/dev_schema.sql" ]; then
              echo "スキーマファイルが見つかりました: digeclip/seeds/dev_schema.sql"
            else
              echo "警告: スキーマファイル digeclip/seeds/dev_schema.sql が見つかりません"
              ls -la digeclip/seeds/ || echo "seeds ディレクトリが見つかりません"
            fi

            # スキーマの直接適用
            echo "スキーマファイルを直接適用しています..."
            if [ -f "digeclip/seeds/dev_schema.sql" ]; then
              timeout 120 PGPASSWORD="${{ secrets.DEV_DB_PASSWORD }}" \
              psql "host=$SUPABASE_PROJECT_ID.supabase.co port=5432 user=postgres dbname=postgres sslmode=require" \
                -f digeclip/seeds/dev_schema.sql > schema_apply.log 2>&1

              SCHEMA_STATUS=$?
              if [ $SCHEMA_STATUS -eq 0 ]; then
                echo "スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
                echo "適用結果サマリー:"
                cat schema_apply.log | grep -v "password\|token\|secret\|key" | tail -n 10
              elif [ $SCHEMA_STATUS -eq 124 ]; then
                echo "スキーマ適用がタイムアウトしました。処理に時間がかかりすぎています。"
                cat schema_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              else
                echo "スキーマ適用に失敗しました。エラー詳細 (終了コード: $SCHEMA_STATUS):"
                cat schema_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              fi
            else
              echo "スキーマファイルが見つからないためスキップします"
            fi

            # シードデータを適用
            echo "シードデータを適用しています..."
            # シードファイルの存在確認
            if [ -f "digeclip/seeds/dev_seed.sql" ]; then
              echo "シードファイルが見つかりました: digeclip/seeds/dev_seed.sql"
              # SQLファイルを直接実行
              timeout 120 PGPASSWORD="${{ secrets.DEV_DB_PASSWORD }}" \
              psql "host=$SUPABASE_PROJECT_ID.supabase.co port=5432 user=postgres dbname=postgres sslmode=require" \
                -f digeclip/seeds/dev_seed.sql > seed_apply.log 2>&1

              SEED_STATUS=$?
              if [ $SEED_STATUS -eq 0 ]; then
                echo "シードデータを適用しました" >> $GITHUB_STEP_SUMMARY
                echo "適用結果サマリー:"
                cat seed_apply.log | grep -v "password\|token\|secret\|key" | tail -n 10
              elif [ $SEED_STATUS -eq 124 ]; then
                echo "シードデータ適用がタイムアウトしました。処理に時間がかかりすぎています。"
                cat seed_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              else
                echo "シードデータ適用に失敗しました。エラー詳細 (終了コード: $SEED_STATUS):"
                cat seed_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              fi
            else
              echo "エラー: シードファイル digeclip/seeds/dev_seed.sql が見つかりません"
              ls -la digeclip/seeds/ || echo "seeds ディレクトリが見つかりません"
              exit 1
            fi

          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            # 本番環境の設定
            SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL_PROD }}"
            SUPABASE_KEY="${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }}"
            SUPABASE_PROJECT_ID=$(echo $SUPABASE_URL | sed 's|https://||' | sed 's|.supabase.co||')
            echo "環境: 本番環境 (スキーマのみ適用)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase プロジェクトID: $SUPABASE_PROJECT_ID"

            # スキーマのみ適用
            echo "本番環境のスキーマを適用しています..."
            export SUPABASE_ACCESS_TOKEN="${{ secrets.SUPABASE_ACCESS_TOKEN }}"
            export PGPASSWORD="${{ secrets.PROD_DB_PASSWORD }}"

            # スキーマファイルの確認
            if [ -f "digeclip/seeds/dev_schema.sql" ]; then
              echo "スキーマファイルが見つかりました: digeclip/seeds/dev_schema.sql"
            else
              echo "警告: スキーマファイル digeclip/seeds/dev_schema.sql が見つかりません"
              ls -la digeclip/seeds/ || echo "seeds ディレクトリが見つかりません"
            fi

            # スキーマの直接適用
            echo "スキーマファイルを直接適用しています..."
            if [ -f "digeclip/seeds/dev_schema.sql" ]; then
              timeout 120 PGPASSWORD="${{ secrets.PROD_DB_PASSWORD }}" \
              psql "host=$SUPABASE_PROJECT_ID.supabase.co port=5432 user=postgres dbname=postgres sslmode=require" \
                -f digeclip/seeds/dev_schema.sql > schema_apply.log 2>&1

              SCHEMA_STATUS=$?
              if [ $SCHEMA_STATUS -eq 0 ]; then
                echo "スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
                echo "適用結果サマリー:"
                cat schema_apply.log | grep -v "password\|token\|secret\|key" | tail -n 10
              elif [ $SCHEMA_STATUS -eq 124 ]; then
                echo "スキーマ適用がタイムアウトしました。処理に時間がかかりすぎています。"
                cat schema_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              else
                echo "スキーマ適用に失敗しました。エラー詳細 (終了コード: $SCHEMA_STATUS):"
                cat schema_apply.log | grep -v "password\|token\|secret\|key"
                exit 1
              fi
            else
              echo "スキーマファイルが見つからないためスキップします"
            fi
          else
            echo "サポートされていないブランチです: $GITHUB_REF"
            exit 1
          fi