name: Supabase デプロイ

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'digeclip/seeds/**'
      - '.github/workflows/supabase-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-supabase:
    name: Supabase スキーマデプロイ
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Supabase CLIをインストール
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 環境変数の設定と適用
        run: |
          # 環境変数を設定
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            # 開発環境の設定
            SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL_DEV }}"
            SUPABASE_KEY="${{ secrets.DEV_SUPABASE_SERVICE_ROLE_KEY }}"
            APPLY_SEED=true
            echo "環境: 開発環境 (シードデータ適用あり)" >> $GITHUB_STEP_SUMMARY

            # プロジェクト参照IDを抽出
            PROJECT_REF=$(echo $SUPABASE_URL | sed 's|https://||' | sed 's|.supabase.co||')
            echo "Supabase プロジェクト参照ID: $PROJECT_REF"

            # スキーマを適用
            echo "開発環境のスキーマを適用しています..."
            SUPABASE_ACCESS_TOKEN="${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
            SUPABASE_DB_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}" \
            supabase db execute --project-ref $PROJECT_REF -f digeclip/seeds/dev_schema.sql

            if [ $? -eq 0 ]; then
              echo "スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
            else
              echo "スキーマ適用に失敗しました"
              exit 1
            fi

            # シードデータを適用（開発環境のみ）
            if [ "$APPLY_SEED" == "true" ]; then
              echo "シードデータを適用しています..."
              SUPABASE_ACCESS_TOKEN="${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
              SUPABASE_DB_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}" \
              supabase db execute --project-ref $PROJECT_REF -f digeclip/seeds/dev_seed.sql

              if [ $? -eq 0 ]; then
                echo "シードデータを適用しました" >> $GITHUB_STEP_SUMMARY
              else
                echo "シードデータ適用に失敗しました"
                exit 1
              fi
            fi

          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            # 本番環境の設定
            SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL_PROD }}"
            SUPABASE_KEY="${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }}"
            echo "環境: 本番環境 (スキーマのみ適用)" >> $GITHUB_STEP_SUMMARY

            # プロジェクト参照IDを抽出
            PROJECT_REF=$(echo $SUPABASE_URL | sed 's|https://||' | sed 's|.supabase.co||')
            echo "Supabase プロジェクト参照ID: $PROJECT_REF"

            # スキーマのみ適用
            echo "本番環境のスキーマを適用しています..."
            SUPABASE_ACCESS_TOKEN="${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
            SUPABASE_DB_PASSWORD="${{ secrets.PROD_DB_PASSWORD }}" \
            supabase db execute --project-ref $PROJECT_REF -f digeclip/seeds/dev_schema.sql

            if [ $? -eq 0 ]; then
              echo "スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
            else
              echo "スキーマ適用に失敗しました"
              exit 1
            fi
          else
            echo "サポートされていないブランチです: $GITHUB_REF"
            exit 1
          fi