name: Supabase デプロイ

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'digeclip/seeds/**'
      - '.github/workflows/supabase-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-supabase:
    name: Supabase スキーマデプロイ
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: PostgreSQLクライアントをインストール
        run: |
          # PostgreSQLクライアントのインストール
          sudo apt-get update
          sudo apt-get install -y postgresql-client dnsutils iputils-ping netcat

          # デバッグ: インストールされたpsqlのバージョンと場所を確認
          which psql || echo "psqlコマンドが見つかりません"
          psql --version || echo "psqlのバージョン取得に失敗"

      - name: Supabase CLI をインストール
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase CLIバージョンを確認
        run: |
          # Supabase CLIのバージョン確認
          supabase --version
          # 利用可能なコマンドの確認
          supabase -h

      - name: 環境変数を設定
        id: set-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            # GitHub Secretsから開発環境の設定を使用
            echo "SUPABASE_PROJECT_ID=${{ secrets.DEV_SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_HOST=db.${{ secrets.DEV_SUPABASE_PROJECT_ID }}.supabase.co" >> $GITHUB_ENV
            echo "SUPABASE_DB_USER=postgres" >> $GITHUB_ENV
            echo "APPLY_SEED=true" >> $GITHUB_ENV
            echo "環境: 開発環境 (シードデータ適用あり)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase Project ID: ${{ secrets.DEV_SUPABASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            # GitHub Secretsから本番環境の設定を使用
            echo "SUPABASE_PROJECT_ID=${{ secrets.PROD_SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_HOST=db.${{ secrets.PROD_SUPABASE_PROJECT_ID }}.supabase.co" >> $GITHUB_ENV
            echo "SUPABASE_DB_USER=postgres" >> $GITHUB_ENV
            echo "APPLY_SEED=false" >> $GITHUB_ENV
            echo "環境: 本番環境 (スキーマのみ適用、シードデータなし)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase Project ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          fi

          # デバッグ: 設定された環境変数の確認（機密情報は除く）
          echo "GITHUB_REF: $GITHUB_REF"
          echo "APPLY_SEED: $APPLY_SEED"
          echo "SUPABASE_DB_HOST: $SUPABASE_DB_HOST"
          echo "SUPABASE_DB_USER: $SUPABASE_DB_USER"

      - name: DNS解決のテスト
        run: |
          # ホスト名のDNS解決をテスト
          echo "DNSテスト: nslookup"
          nslookup $SUPABASE_DB_HOST || echo "nslookup失敗"

          echo "DNSテスト: dig"
          dig $SUPABASE_DB_HOST +short || echo "dig失敗"

          echo "DNSテスト: dig A レコード"
          dig A $SUPABASE_DB_HOST +short || echo "dig A失敗"

          echo "DNSテスト: dig AAAA レコード"
          dig AAAA $SUPABASE_DB_HOST +short || echo "dig AAAA失敗"

          # ネットワーク接続性テスト (IPv4)
          echo "接続テスト: ping"
          ping -c 3 -4 $SUPABASE_DB_HOST || echo "ping失敗"

          echo "接続テスト: nc (IPv4)"
          nc -vz -4 $SUPABASE_DB_HOST 5432 || echo "nc接続テスト失敗"

      - name: 接続情報の検証
        run: |
          # Supabase CLIの接続テスト
          echo "Supabase CLIの接続テスト中..."
          # ドキュメント通りに必要な環境変数が設定されているか確認
          echo "必要な環境変数: SUPABASE_ACCESS_TOKEN, SUPABASE_PROJECT_ID, SUPABASE_DB_PASSWORD"

          # プロジェクト一覧を取得して接続テスト
          supabase projects list --debug > cli_test.log 2>&1

          if [ $? -ne 0 ]; then
            echo "Supabase CLI接続テストに失敗しました。詳細:"
            cat cli_test.log | grep -v "password\|token\|secret\|key"
            # 失敗してもプロセスを続行
            echo "警告: Supabase CLI接続テストに失敗しましたが、続行します"
          else
            echo "Supabase CLI接続テスト成功"
          fi

      - name: デプロイ前のスキーマ確認
        run: |
          # スキーマファイルの存在確認
          if [[ ! -f "digeclip/seeds/dev_schema.sql" ]]; then
            echo "Error: digeclip/seeds/dev_schema.sql ファイルが見つかりません。"
            exit 1
          fi

          # デバッグ: スキーマファイルの内容確認（最初の10行）
          echo "スキーマファイルの確認（最初の10行）:"
          head -n 10 digeclip/seeds/dev_schema.sql

      - name: psql接続テスト（IPv4強制）
        run: |
          # psqlでの接続テスト（IPv4強制）
          echo "psqlの接続テスト (IPv4強制)..."
          # -4 フラグでIPv4接続を強制
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -4 -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -c "SELECT current_database(), current_user" || echo "psql接続テストに失敗しました"

      - name: スキーマをデプロイ
        continue-on-error: true  # エラーが発生しても次のステップに進む
        run: |
          # スキーマを適用（IPv4強制）
          echo "psqlを使用してスキーマを適用しています (IPv4強制)..."
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -4 -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -f digeclip/seeds/dev_schema.sql

          DEPLOY_RESULT=$?
          if [ $DEPLOY_RESULT -eq 0 ]; then
            if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              echo "開発環境用スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
            elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "本番環境用スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "スキーマ適用中にエラーが発生しました。終了コード: $DEPLOY_RESULT" >> $GITHUB_STEP_SUMMARY

            # Supabase CLIを使用した代替方法を試す
            echo "Supabase CLIを使用した代替方法を試みます..."
            supabase db push --db-url "postgresql://$SUPABASE_DB_USER:$SUPABASE_DB_PASSWORD@$SUPABASE_DB_HOST:5432/postgres" digeclip/seeds/dev_schema.sql || echo "Supabase CLI db pushにも失敗しました"
          fi

      - name: 開発環境にシードデータを適用
        if: env.APPLY_SEED == 'true'
        continue-on-error: true  # エラーが発生しても次のステップに進む
        run: |
          # シードファイルの存在確認
          if [[ ! -f "digeclip/seeds/dev_seed.sql" ]]; then
            echo "Error: digeclip/seeds/dev_seed.sql ファイルが見つかりません。"
            exit 1
          fi

          # デバッグ: シードファイルの内容確認（最初の10行）
          echo "シードファイルの確認（最初の10行）:"
          head -n 10 digeclip/seeds/dev_seed.sql

          echo "開発環境用シードデータを適用します (IPv4強制)"
          # psqlを使用してシードデータを適用（IPv4強制）
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -4 -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -f digeclip/seeds/dev_seed.sql

          SEED_RESULT=$?
          if [ $SEED_RESULT -eq 0 ]; then
            echo "開発環境用シードデータを適用しました" >> $GITHUB_STEP_SUMMARY
          else
            echo "シードデータ適用中にエラーが発生しました。終了コード: $SEED_RESULT" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 代替接続方法の試行
        run: |
          echo "代替接続方法のテスト中..."
          echo "Supabase CLIを使用したデータベース情報の取得："
          supabase db info || echo "db info取得に失敗しました"

          echo "直接URLでの接続テスト："
          # 環境変数の一部隠蔽
          DB_HOST_DOMAIN=$(echo $SUPABASE_DB_HOST | cut -d'.' -f2-)
          echo "接続先ドメイン: $DB_HOST_DOMAIN"

          # デバッグ用にIPv4アドレスを直接使用する可能性のテスト
          echo "nslookupでIPv4アドレスを取得します："
          IP_ADDR=$(dig +short A $SUPABASE_DB_HOST | head -n1)
          if [ -n "$IP_ADDR" ]; then
            echo "IPアドレス: $IP_ADDR が見つかりました"
            echo "IPアドレスを直接使用して接続テスト："
            PGPASSWORD=$SUPABASE_DB_PASSWORD psql -h $IP_ADDR -U $SUPABASE_DB_USER -p 5432 -d postgres -c "SELECT current_database()" || echo "IPアドレスでの接続に失敗しました"
          else
            echo "IPアドレスの解決に失敗しました"
          fi

      - name: デプロイ結果の確認
        run: |
          echo "デプロイ処理が完了しました"
          echo "日時: $(date)"
          echo "環境: $([[ $GITHUB_REF == 'refs/heads/dev' ]] && echo '開発環境' || echo '本番環境')"
          echo "GitHub Action 実行URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "実行結果の要約を確認してください。"