name: Supabase デプロイ

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'digeclip/seeds/**'
      - '.github/workflows/supabase-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-supabase:
    name: Supabase スキーマデプロイ
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: PostgreSQLクライアントをインストール
        run: |
          # PostgreSQLクライアントのインストール
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          # デバッグ: インストールされたpsqlのバージョンと場所を確認
          which psql || echo "psqlコマンドが見つかりません"
          psql --version || echo "psqlのバージョン取得に失敗"

      - name: Supabase CLI をインストール
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase CLIバージョンを確認
        run: |
          # Supabase CLIのバージョン確認
          supabase --version
          # 利用可能なコマンドの確認
          supabase -h

      - name: 環境変数を設定
        id: set-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            # GitHub Secretsから開発環境の設定を使用
            echo "SUPABASE_PROJECT_ID=${{ secrets.DEV_SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_HOST=db.${{ secrets.DEV_SUPABASE_PROJECT_ID }}.supabase.co" >> $GITHUB_ENV
            echo "SUPABASE_DB_USER=postgres" >> $GITHUB_ENV
            echo "APPLY_SEED=true" >> $GITHUB_ENV
            echo "環境: 開発環境 (シードデータ適用あり)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase Project ID: ${{ secrets.DEV_SUPABASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            # GitHub Secretsから本番環境の設定を使用
            echo "SUPABASE_PROJECT_ID=${{ secrets.PROD_SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "SUPABASE_DB_HOST=db.${{ secrets.PROD_SUPABASE_PROJECT_ID }}.supabase.co" >> $GITHUB_ENV
            echo "SUPABASE_DB_USER=postgres" >> $GITHUB_ENV
            echo "APPLY_SEED=false" >> $GITHUB_ENV
            echo "環境: 本番環境 (スキーマのみ適用、シードデータなし)" >> $GITHUB_STEP_SUMMARY
            echo "Supabase Project ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          fi

          # デバッグ: 設定された環境変数の確認（機密情報は除く）
          echo "GITHUB_REF: $GITHUB_REF"
          echo "APPLY_SEED: $APPLY_SEED"
          echo "SUPABASE_DB_HOST: $SUPABASE_DB_HOST"
          echo "SUPABASE_DB_USER: $SUPABASE_DB_USER"

      - name: 接続情報の検証
        run: |
          # Supabase CLIの接続テスト
          echo "Supabase CLIの接続テスト中..."
          # ドキュメント通りに必要な環境変数が設定されているか確認
          echo "必要な環境変数: SUPABASE_ACCESS_TOKEN, SUPABASE_PROJECT_ID, SUPABASE_DB_PASSWORD"

          # プロジェクト一覧を取得して接続テスト
          supabase projects list --debug > cli_test.log 2>&1

          if [ $? -ne 0 ]; then
            echo "Supabase CLI接続テストに失敗しました。詳細:"
            cat cli_test.log | grep -v "password\|token\|secret\|key"
            exit 1
          else
            echo "Supabase CLI接続テスト成功"
          fi

      - name: スキーマをデプロイ
        run: |
          # スキーマファイルの存在確認
          if [[ ! -f "digeclip/seeds/dev_schema.sql" ]]; then
            echo "Error: digeclip/seeds/dev_schema.sql ファイルが見つかりません。"
            exit 1
          fi

          # デバッグ: スキーマファイルの内容確認（最初の10行）
          echo "スキーマファイルの確認（最初の10行）:"
          head -n 10 digeclip/seeds/dev_schema.sql

          # psqlでの接続と実行テスト
          echo "psqlの接続テスト..."
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -c "SELECT current_database(), current_user" || echo "psql接続テストに失敗しました"

          # スキーマを適用
          echo "psqlを使用してスキーマを適用しています..."
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -f digeclip/seeds/dev_schema.sql

          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "開発環境用スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "本番環境用スキーマを適用しました" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 開発環境にシードデータを適用
        if: env.APPLY_SEED == 'true'
        run: |
          # シードファイルの存在確認
          if [[ ! -f "digeclip/seeds/dev_seed.sql" ]]; then
            echo "Error: digeclip/seeds/dev_seed.sql ファイルが見つかりません。"
            exit 1
          fi

          # デバッグ: シードファイルの内容確認（最初の10行）
          echo "シードファイルの確認（最初の10行）:"
          head -n 10 digeclip/seeds/dev_seed.sql

          echo "開発環境用シードデータを適用します"
          # psqlを使用してシードデータを適用
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql -h $SUPABASE_DB_HOST -U $SUPABASE_DB_USER -p 5432 -d postgres -f digeclip/seeds/dev_seed.sql

          echo "開発環境用シードデータを適用しました" >> $GITHUB_STEP_SUMMARY

      - name: デプロイ結果の確認
        run: |
          echo "デプロイ処理が完了しました"
          echo "日時: $(date)"
          echo "環境: $([[ $GITHUB_REF == 'refs/heads/dev' ]] && echo '開発環境' || echo '本番環境')"
          echo "GitHub Action 実行URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"