name: テスト

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 依存関係のインストール
        run: |
          echo "現在のディレクトリ構造を確認"
          ls -la

          if [ -f "digeclip/package.json" ]; then
            cd digeclip
            npm install
          else
            if [ -f "package.json" ]; then
              npm install
            else
              echo "package.jsonが見つかりません。ディレクトリ構造を確認します。"
              find . -name "package.json" -type f
            fi
          fi

      - name: テストの実行
        id: run_test
        run: |
          TEST_SUCCESS=0
          if [ -f "digeclip/package.json" ]; then
            cd digeclip
            if grep -q '"test":' package.json; then
              npm test && TEST_SUCCESS=1 || echo "テストスクリプトの実行に失敗しました"
            else
              echo "警告: package.jsonにテストスクリプトが定義されていません"
            fi
          else
            if [ -f "package.json" ]; then
              if grep -q '"test":' package.json; then
                npm test && TEST_SUCCESS=1 || echo "テストスクリプトの実行に失敗しました"
              else
                echo "警告: package.jsonにテストスクリプトが定義されていません"
              fi
            else
              PKG_DIR=$(find . -name "package.json" -type f | head -1 | xargs dirname)
              if [ ! -z "$PKG_DIR" ]; then
                cd $PKG_DIR
                if grep -q '"test":' package.json; then
                  npm test && TEST_SUCCESS=1 || echo "テストスクリプトの実行に失敗しました"
                else
                  echo "警告: package.jsonにテストスクリプトが定義されていません"
                fi
              else
                echo "package.jsonが見つからないためテストを実行できません"
              fi
            fi
          fi
          echo "test_success=$TEST_SUCCESS" >> $GITHUB_OUTPUT

      - name: カバレッジレポートのアップロード
        if: steps.run_test.outputs.test_success == '1'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./digeclip/coverage
          fail_ci_if_error: false