name: テスト実行

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 依存関係のインストール
        run: |
          echo "現在のディレクトリ構造を確認"
          ls -la

          if [ -f "package.json" ]; then
            npm install
          else
            echo "package.jsonが見つかりません。ディレクトリ構造を確認します。"
            find . -name "package.json" -type f

            # package.jsonが見つかった場所に移動
            PKG_DIR=$(find . -name "package.json" -type f | head -1 | xargs dirname)
            if [ ! -z "$PKG_DIR" ]; then
              echo "package.jsonが見つかりました: $PKG_DIR"
              cd $PKG_DIR
              npm install
            fi
          fi
      - name: テスト実行
        id: run_test
        run: |
          TEST_SUCCESS=0
          if [ -f "package.json" ]; then
            if grep -q '"test":' package.json; then
              npm test -- --coverage && TEST_SUCCESS=1 || echo "テストスクリプトの実行に失敗しました"
            else
              echo "警告: package.jsonにテストスクリプトが定義されていません"
            fi
          else
            PKG_DIR=$(find . -name "package.json" -type f | head -1 | xargs dirname)
            if [ ! -z "$PKG_DIR" ]; then
              cd $PKG_DIR
              if grep -q '"test":' package.json; then
                npm test -- --coverage && TEST_SUCCESS=1 || echo "テストスクリプトの実行に失敗しました"
              else
                echo "警告: package.jsonにテストスクリプトが定義されていません"
              fi
            else
              echo "package.jsonが見つからないためテストを実行できません"
            fi
          fi
          echo "test_success=$TEST_SUCCESS" >> $GITHUB_OUTPUT

      - name: カバレッジレポートのアップロード
        if: steps.run_test.outputs.test_success == '1'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false